### ISSUE TITLE
Coed review 

### ISSUE THREAD

**Issue by Aleksandr112Kupruk222** [eazzyone11/OOP-#1]
-The code presented requires addtional comments , as at the moments there basicly few comments, this makes it harder to read the code and understand its inner work.
- Validation is sufficent and does not produce any errors 
- One issue that i noticed is that you mixed up the names of the classes that you produced, class validation acts as a class that supposed to be name testing and testing acts as validation.
- https://github.com/eazzyone11/OOP-/blob/a33c6dac138c8e8fff1c9f1b6e6a6fd6ea680483/CMP1903M%20A01%202223/CMP1903M%20A01%202223/Validation.cs#L9-L52
- 
https://github.com/eazzyone11/OOP-/blob/a33c6dac138c8e8fff1c9f1b6e6a6fd6ea680483/CMP1903M%20A01%202223/CMP1903M%20A01%202223/Testing.cs#L7-L37

This makes it confucing reading code as the naming convention does not follow common sense, especially when you pass parameters inside the classes.

in overall the code quality is high , however confusion with classes and lack of comments needs working

**Comment by eazzyone11** [comment]
![image](https://user-images.githubusercontent.com/127356300/224058580-be061165-d642-4175-9adc-e9134adaaf64.png)
more comments have been added and the classes has been renamed 
![image](https://user-images.githubusercontent.com/127356300/224058957-d7dd4c17-13c1-4c36-aa29-9e8468258a7a.png)
